# Generated by Django 3.1.7 on 2021-02-25 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/owner/')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2021, 2, 25, 17, 10, 49, 635660))),
            ],
        ),
    ]
